#TODO: Сделать перед стартом compose команду sudo setfacl --modify user:$USER:rw /var/run/docker.sock

version: "3.9"
services:
  postgres:
    container_name: analyze-io-db
    image: postgres:13.3
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: analyze-io-pgadmin
    image: dpage/pgadmin4:5.7
    env_file:
      - .pgadmin.env
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

  analyze-io-backend:
    container_name: analyze-io-app
    image: analyze-io-backend
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:3000"
    volumes:
      - ./resources:/app/resources
    networks:
      - postgres  

networks:
  postgres:
    driver: bridge