#TODO: Сделать перед стартом compose команду sudo setfacl --modify user:$USER:rw /var/run/docker.sock

version: '3.9'
services:
  postgres:
    container_name: analyze-io-db
    image: postgres:13.3
    env_file:
      - .env
    volumes:
      - ${AIO_POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: analyze-io-pgadmin
    depends_on:
      - postgres
    image: dpage/pgadmin4:5.7
    env_file:
      - .env
    volumes:
      - ${AIO_PGADMIN_VOLUME}:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped
    networks:
      - postgres

  #analyze-io-backend:
  #  container_name: analyze-io-backend
  #  image: analyze-io-backend
  #  depends_on:
  #    - postgres
  #  env_file:
  #    - .env
  #  ports:
  #    - '8000:${AIO_PORT}'
  #  volumes:
  #    - ${AIO_RESOURCES_VOLUME}:/app/${AIO_FILE_STORAGE}
  #  networks:
  #    - postgres     

networks:
  postgres:
    driver: bridge      